# Generated by Django 3.2.15 on 2023-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingtravel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
