# Generated by Django 3.2.15 on 2023-06-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_schedulingtravel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingtravel',
            name='user',
        ),
    ]
