# Generated by Django 3.2.15 on 2023-06-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_commentsangency_contactus_travelinsurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactUs',
        ),
    ]
